### ISSUE TITLE
Redirect "save" to "save as..." on a new project?

### ISSUE THREAD

**Issue by ksugar** [mastodon-sc/mastodon#130]
### Summary

The *save* button and *Save Project* command fail with the following error when the project is created from `.h5`/`.xml`.
The *save as...* button works.

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mastodon.mamut.project.MamutProject.openForWriting(MamutProject.java:170)
	at org.mastodon.mamut.ProjectManager.saveProject(ProjectManager.java:317)
	at org.mastodon.mamut.ProjectManager.saveProject(ProjectManager.java:303)
	at org.scijava.ui.behaviour.util.RunnableAction.actionPerformed(RunnableAction.java:47)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### How to reproduce

1. Create a new Mastodon project from `.h5`/`.xml`
2. Run `Save Project`

#### Environment

The latest version of Mastodon on Fiji running on Ubuntu 18.04 (64-bit)
Version on the launcher panel: `1.0.0-beta-18-SNAPSHOT-11121b463e1d7c1221dab58642b973882df8ea7f`

### Investigation

`projectRoot` at org.mastodon.mamut.project.MamutProject.openForWriting(MamutProject.java:170) is `null`

### Suggestioin

Redirect to `save as...` when the project is newly created.

**Comment by tinevez** [comment]
I can reproduce the bug. 

Normally the `Save` button means to simply overwrite the project file with the new data, without showing the user a file dialog. You can see it as a quick save.

The issue appears when a Mastodon file  was not specified, as is the case just after creating it. Your suggestion is correct and I will implement it.
