### ISSUE TITLE
Exception during Fiji startup

### ISSUE THREAD

**Issue by danielmccusker** [mastodon-sc/mastodon#192]
When I open the Mastodon launcher in Fiji, the console throws the warning

[WARNING] 1 exceptions occurred during plugin discovery.

And when I try to start a new Mastodon project from an XML file, I get the following exception

Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: bdv.spimdata.XmlIoSpimDataMinimal.load(Ljava/lang/String;)Lbdv/spimdata/SpimDataMinimal;
	at org.mastodon.mamut.launcher.LauncherGUI$OpenBDVPanel.checkBDVFile(LauncherGUI.java:376)
	at org.mastodon.mamut.launcher.LauncherGUI$OpenBDVPanel.lambda$null$0(LauncherGUI.java:366)
	at org.mastodon.mamut.launcher.LauncherUtil.browseToBDVFile(LauncherUtil.java:137)
	at org.mastodon.mamut.launcher.LauncherGUI$OpenBDVPanel.lambda$new$1(LauncherGUI.java:363)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

After which nothing happens when I click "create". Is this a known issue?

**Comment by tinevez** [comment]
Yes! 
caused by an update of BDV libraries.
working on it.

**Comment by mschin1** [comment]
Thank you for working on it!

Just here to say that I got a similar issue when trying to open a mastodon file from yesterday. Also the spimdata but more exceptions and colormodes.yaml 

[WARNING] 5 exceptions occurred during plugin discovery.
Feature color mode file /home/schindle/.mastodon/colormodes.yaml not found. Using builtin styles.
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: bdv.spimdata.XmlIoSpimDataMinimal.load(Ljava/lang/String;)Lbdv/spimdata/SpimDataMinimal;
	at org.mastodon.mamut.ProjectManager.open(ProjectManager.java:364)
	at org.mastodon.mamut.launcher.MastodonLauncher.lambda$null$16(MastodonLauncher.java:411)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by tinevez** [comment]
Hello @danielmccusker and @mschin1 
I uploaded a new version that should fix this. Can you confirm it does?
More discussions on this forum topic: 
https://forum.image.sc/t/mastodon-and-mamut-are-currently-broken-after-fiji-update-working-on-fixes-right-now/71856/5

**Comment by mschin1** [comment]
Hello! Sorry for the delay! My files now managed to open again and it seems to work fine!

Thank you!!!
