### ISSUE TITLE
Mastodon Memory Leak

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon#225]
## Problem description

I noticed that mastodon objects like WindowManger, ProjectManager, AppModel etc. don't get garbage collected after the project is closed.

This can be a problem for users. Fiji might run out of memory when opening a large number of Mastodon projects, one after the other. The [Eclipse Memory Analyzer](https://www.eclipse.org/mat/) is a handy tool to inspect such problems. The `org.mastodon.spatial.SpatioTemporalIndexImpRebuilderThread` seems to stay in memory and keeps a reference to the ModelGraph.

## TODOs

- [x] Find why the SpatioTemporalIndexImpRebuilderThread does not stop after Mastodon is closed. Fix that problem.
- [x] Check if garbage collection properly cleans up the Mastodon WindowManager and ModelGraph.

## Expected Behavior

All Mastodon related objects (WindowManager, ProjectManager, AppModel, ModelGraph, etc. ) get garbage collected after a Mastodon project is closed.

**Comment by tinevez** [comment]
Argh the horror.

**Comment by maarzt** [comment]
The following few lines of code are enough to trigger an OutOfMemoryException:
```java
package org.mastodon.mamut.tomancak;

import org.junit.Test;
import org.mastodon.mamut.model.Model;

public class MastodonMemoryTest
{
	@Test
	public void test() {
		for ( int i = 0; i < 100; i++ )
		{
			new Model();
		}
	}
}
```

The problem seems to be related to the UndoRedoStack. See stack trace:
```
java.lang.OutOfMemoryError: Java heap space

	at org.mastodon.undo.ByteArrayUndoRedoStack.<init>(ByteArrayUndoRedoStack.java:122)
	at org.mastodon.undo.GraphUndoRedoStack.<init>(GraphUndoRedoStack.java:90)
	at org.mastodon.undo.GraphUndoRecorder.<init>(GraphUndoRecorder.java:98)
	at org.mastodon.mamut.model.Model.<init>(Model.java:178)
	at org.mastodon.mamut.model.Model.<init>(Model.java:122)
	at org.mastodon.mamut.tomancak.MastodonMemoryTest.test(MastodonMemoryTest.java:12)
```

**Comment by stefanhahmann** [comment]
@maarzt Could you ask for review/approval/merge of the related PR https://github.com/bigdataviewer/bigdataviewer-core/pull/163 so that the temporarily introduced PainterThread of this PR does not live longer than necessary?

**Comment by tpietzsch** [comment]
I'll review it today

**Comment by tinevez** [comment]
Could we depend on  bigdataviewer-core-10.4.7 in mastodon and use the code from there? Or do we have specifics in Mastodon?

**Comment by maarzt** [comment]
This issue if fixed with the following PRs being merged and mastodon-graph-1.0.0-beta-24 and bigdataviewer-core-10.4.7 being released:
- https://github.com/mastodon-sc/mastodon-graph/pull/14
- https://github.com/mastodon-sc/mastodon/pull/244
- https://github.com/bigdataviewer/bigdataviewer-core/pull/163
