### ISSUE TITLE
Mastodon Exceptions Occurred During Plugin Discovery 

### ISSUE THREAD

**Issue by allyrp** [mastodon-sc/mastodon#276]
When opening Mastodon and trying to open a file I am getting these errors. Looking for some solutions to the problem. 

[WARNING] 1 exceptions occurred during plugin discovery.
Keymap list file C:\Users\pancal01\.mastodon\keymaps\keymaps.yaml not found. Using builtin styles.
[WARNING] 1 exceptions occurred during plugin discovery.
Settings file C:\Users\pancal01/.mastodon/rendersettings.yaml not found. Using builtin settings.
Settings file C:\Users\pancal01/.mastodon/trackschemestyles.yaml not found. Using builtin settings.
Settings file C:\Users\pancal01/.mastodon/datagraphstyles.yaml not found. Using builtin settings.
Settings file C:\Users\pancal01/.mastodon/colormodes.yaml not found. Using builtin settings.
Exception in thread "Thread-11" java.lang.NoClassDefFoundError: org/mastodon/mamut/plugin/MamutPluginAppModel
	at ch.epfl.biop.mastodon.MamutWarperPlugin.setAppPluginModel(MamutWarperPlugin.java:26)
	at org.mastodon.mamut.ProjectModel.lambda$discoverPlugins$1(ProjectModel.java:208)
	at org.mastodon.app.plugin.PluginUtils.lambda$forEachDiscoveredPlugin$0(PluginUtils.java:63)
	at org.mastodon.app.plugin.PluginUtils.forEachDiscoveredPlugin(PluginUtils.java:96)
	at org.mastodon.app.plugin.PluginUtils.forEachDiscoveredPlugin(PluginUtils.java:64)
	at org.mastodon.mamut.ProjectModel.discoverPlugins(ProjectModel.java:211)
	at org.mastodon.mamut.ProjectModel.<init>(ProjectModel.java:132)
	at org.mastodon.mamut.ProjectModel.create(ProjectModel.java:250)
	at org.mastodon.mamut.io.ProjectLoader.open(ProjectLoader.java:193)
	at org.mastodon.mamut.launcher.LauncherUtil.openWithDialog(LauncherUtil.java:332)
	at org.mastodon.mamut.launcher.LauncherUtil.createProjectFromBdvFileWithDialog(LauncherUtil.java:149)
	at org.mastodon.mamut.launcher.MastodonLauncher.lambda$createNewProject$16(MastodonLauncher.java:340)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.mastodon.mamut.plugin.MamutPluginAppModel
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more

**Comment by tinevez** [comment]
Hello.
It seems like a conflict between beta-26 and beta-28 classes. 
Can you truy the following:
1/ Try installing Mastodon on a freshly downloaded Fiji, with no other update-sites subscribed.
2/ Can you list the mastodon-*.jar files you have in the `jars/` folder of the culprit Fiji install?
