### ISSUE TITLE
Compute features option not working in Mastodon

### ISSUE THREAD

**Issue by sundar07** [mastodon-sc/mastodon#280]
Hi Jean Yves,
I have been using Mastodon plugin in FIJI to track cells manually in zebrafish embryos. When I finished tracking and went for “Compute Features” option, I get the following error:

Exception in thread “Feature computation thread” java.lang.NoClassDefFoundError: io/humble/ferry/AtomicInteger
at org.mastodon.mamut.feature.SpotTrackIDFeatureComputer.run(SpotTrackIDFeatureComputer.java:77)
at org.mastodon.feature.DefaultFeatureComputerService.compute(DefaultFeatureComputerService.java:261)
at org.mastodon.mamut.feature.MamutFeatureComputerService.compute(MamutFeatureComputerService.java:96)
at org.mastodon.mamut.MamutFeatureComputation$MyFeatureComputerService.compute(MamutFeatureComputation.java:163)
at org.mastodon.feature.ui.FeatureComputationController$2.run(FeatureComputationController.java:129)
Caused by: java.lang.ClassNotFoundException: io.humble.ferry.AtomicInteger
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
… 5 more

I have updated java, updated fiji, tried uninstalling and re-installing Mastodon, but still have the same problem. Any suggestions?

Thanks
Sundar

**Comment by sundar07** [comment]
Hi Stefan,
Thanks for your reply. I am very much an end user and I do not particularly understand how to change what you have suggested. Can you detail this a bit more? Or does this change has to happen from Mastodon's end?

**Comment by stefanhahmann** [comment]
![GIF 21 02 2024 10-16-15](https://github.com/mastodon-sc/mastodon/assets/10515534/959a4ecc-f138-49d0-85e7-ccf7207fc842)

**Comment by stefanhahmann** [comment]
Currently this dependency is needed: https://sites.imagej.net/Humble-Video/jars/humble-video-noarch-0.3.0.jar-20221115102504

**Comment by sundar07** [comment]
It works now! Thanks a lot for the work around!!

**Comment by tinevez** [comment]
It is an import error. I imported `AtomicInteger` from humble video, while I should have imported the one in `java.lang`. 
I did not see the error because I am distracted and I had humble video in my class path when compiling.
I am so sorry >.<

**Comment by stefanhahmann** [comment]
> It is an import error. I imported `AtomicInteger` from humble video, while I should have imported the one in `java.lang`. I did not see the error because I am distracted and I had humble video in my class path when compiling. I am so sorry >.<

Cf.:
https://github.com/mastodon-sc/mastodon/pull/281
